addons:
  apt:
    packages:
    - apache2
    - apache2-suexec-pristine
    # - elinks


script:
- |
  service apache2 status
  if [ 0 -eq $? ] ; then
    exit 1
  else
    exit 0
  fi
# - elinks -dump-color-mode 4 -dump http://localhost:80
